# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-17 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='genre',
        ),
    ]
